#!/bin/bash

template="$(chezmoi source-path 2>/dev/null)/chezmoi-cfg-tmpl"
[ ! -f "$template" ] && template="$XDG_DATA_HOME/chezmoi/chezmoi-cfg-tmpl"
[ ! -f "$template" ] && echo "Tempate file: '$template' not found" && exit 1;
chezmoi_cfg_dir="$XDG_CONFIG_HOME/chezmoi"
destination="$chezmoi_cfg_dir/chezmoi.yaml"

if [ "$(find "$chezmoi_cfg_dir" -type f | grep -v '.boltdb$' | wc -l)" -gt 1 ]; then
  echo "Multiple configs files found in '$chezmoi_cfg_dir'. Exiting";
  exit 1;
fi

_render_template() {
  sed '
  s/%%!profile!%%/'"$profile"'/g
  s~%%!browser!%%~'$browser'~g
  s/%%!u_email!%%/'"$u_email"'/g
  s/%%!u_fullname!%%/'"$u_fullname"'/g
  s/%%!pid1!%%/'"$pid1"'/g
  ' "$template"
}

# PROFILE
[ -z "$def_profile" ] && def_profile="$(chezmoi execute-template '{{.conf.profile}}' 2>/dev/null)"
[ -z "$def_profile" ] && [ "$(chezmoi execute-template '{{.chezmoi.os}}' 2>/dev/null)" = 'android' ] && def_profile="phone"
[ -z "$def_profile" ] && [ "$(chezmoi execute-template '{{.chezmoi.osRelease.id}}' 2>/dev/null)" = 'debian' ] && def_profile="server"
[ -z "$def_profile" ] && [ -n "$SSH_CONNECTION" ] && def_profile="server"
[ -z "$def_profile" ] && def_profile="pc"
printf "Profile [pc|server|phone] (default: '$def_profile'): "
read -r profile
[ -z "$profile" ] && profile="$def_profile"
case "$profile" in
  pc|server|phone) :;;
  *) echo "Bad profile: $profile"; exit 1;;
esac


# BROWSER
browsers="$(command -v brave-beta brave firefox-developer-edition firefox chromium links false 2>/dev/null)"
[ -z "$def_browser" ] && def_browser="$(chezmoi execute-template '{{.conf.browser}}' 2>/dev/null)"
[ -z "$def_browser" ] && def_browser="$BROWSER"
[ -z "$def_browser" ] && def_browser="$(echo "$browsers" | head -n1)"
echo "
Available browsers (name or false for none):
$(echo "$browsers" | awk '{print " - " $0}')
"
printf "Select browser (default: '$def_browser'): "
read -r browser
[ -z "$browser" ] && browser="$def_browser"
if command -v "$browser" >/dev/null 2>&1; then
  browser="$(command -v "$browser" 2>/dev/null)"
else
  echo "No such browser: '$browser'"; exit 1;
fi


# USER EMAIL
[ -z "$def_u_email" ] && def_u_email="$(chezmoi execute-template '{{.conf.user.email}}' 2>/dev/null)"
[ -z "$def_u_email" ] && def_u_email="$(git config --get user.email 2>/dev/null)"
printf "User u_email (default: '$def_u_email'): "
read -r u_email
[ -z "$u_email" ] && u_email="$def_u_email"
[ -z "$u_email" ] && echo "u_email cannot be empty!" && exit 1


# USER NAME
[ -z "$def_u_fullname" ] && def_u_fullname="$(chezmoi execute-template '{{.conf.user.fullname}}' 2>/dev/null)"
[ -z "$def_u_fullname" ] && def_u_fullname="$(git config --get user.name 2>/dev/null)"
[ -z "$def_u_fullname" ] && def_u_fullname="$USER"
printf "User fullname (default: '$def_u_fullname'): "
read -r u_fullname
[ -z "$u_fullname" ] && u_fullname="$def_u_fullname"
[ -z "$u_fullname" ] && echo "u_fullname cannot be empty!" && exit 1


# PID1
[ -z "$def_pid1" ] && def_pid1="$(chezmoi execute-template '{{.conf.pid1}}' 2>/dev/null)"
[ -z "$def_pid1" ] && test -f /proc/1/comm && def_pid1="$(cat /proc/1/comm)"
printf "pid1 (init system) (default: '$def_pid1'): "
read -r pid1
[ -z "$pid1" ] && pid1="$def_pid1"


echo "
Selected:
  profile:    '$profile'
  browser:    '$browser'
  pid1:       '$pid1'
  u_email:    '$u_email'
  u_fullname: '$u_fullname'
"

tmpf="$(mktemp)"
_render_template > "$tmpf"

if ! diff --color "$destination" "$tmpf"; then
  printf "Apply changes? [y/N]:"; read -r reply;
  case "$reply" in
    y|yes|Y|YES) cp -vf "$tmpf" "$destination";;
    *) echo "No changes have been made";;
  esac
else
  echo "No changes found"
fi
