#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
userresources="$HOME/.config/x11/xresources"
usermodmap="$HOME/.config/x11/xmodmap"
userkeybindings="$HOME/.config/x11/xbindkeysrc"
#sysresources=/etc/X11/xinit/.Xresources
#sysmodmap=/etc/X11/xinit/.Xmodmap

# export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# merge in defaults and keymaps
#if [ -f $sysresources ]; then
#    xrdb -merge $sysresources
#fi
#if [ -f $sysmodmap ]; then
#    xmodmap $sysmodmap
#fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
if [ -f "$userkeybindings" ]; then
    xbindkeys -f "$userkeybindings"
fi
# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# X server settings
xsetroot -cursor_name left_ptr &
# for debug
# env > .xenv
# dpms off it does nothind for destop
xset dpms 1200 3600 7200 
xset +dpms
# disable screensaver todo: enable if using xscreensaver
xset s off
# autolock
xautolock -time 10 -notify 20 -notifier 'notify-send -u critical -t 20 "Screen lock in 20s"' -corners '000-' -locker 'lockscreen' &

# startup programs
dunst &
udiskie -s &
picom -b --experimental-backends &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
clipmenud &
xbindkeys &

# select session
session='i3 --shmlog-size 0'
#session='bspwm'
#session='xmonad'

# shellcheck disable=SC2086
exec $session
