#!/bin/sh

echo "Starting waybar"

# shutdown waybars
if pgrep -u "$(id -u)" -x waybar >/dev/null; then
  echo "killing existing waybars"
  killall -q waybar

  # wait until shutdown of existing waybars
  cycles=10
  while pgrep -u "$(id -u)" -x waybar >/dev/null; do
    [ $cycles -le 0 ] && break;
    sleep 0.5;
    cycles=$((cycles-1))
  done
fi

WAYBAR_CFG_DIR="$XDG_CONFIG_HOME/waybar"

cfg="$(mktemp -p /tmp waybarconfig-XXXXXXXX.log)"
(
  cpp -undef -P "$WAYBAR_CFG_DIR/default.jsonc";
  if [ -e "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.jsonc" ]; then
    cpp -undef -P "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.jsonc" 2>/dev/null
  fi
  if [ -e "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.local.jsonc" ]; then
    cpp -undef -P "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.local.jsonc" 2>/dev/null
  fi
) | jq -r 'reduce inputs as $i (.; . *= $i)' >"$cfg"

exec waybar -c "$cfg"
