#!/bin/sh

echo "Killing existing waybars"
killwait waybar

WAYBAR_CFG_DIR="$XDG_CONFIG_HOME/waybar"

cfg="$(mktemp -p /tmp waybarconfig-XXXXXXXX.log)"
(
  cpp -undef -P "$WAYBAR_CFG_DIR/default.jsonc";
  if [ -e "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.jsonc" ]; then
    cpp -undef -P "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.jsonc" 2>/dev/null
  fi
  if [ -e "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.local.jsonc" ]; then
    cpp -undef -P "$WAYBAR_CFG_DIR/$DESKTOP_SESSION.local.jsonc" 2>/dev/null
  fi
) | jq -r 'reduce inputs as $i (.; . *= $i)' >"$cfg"

echo "Starting waybar"
exec waybar -c "$cfg"
