#!/bin/sh

userresources="$HOME/.config/x11/xresources"
userkeybindings="$HOME/.config/x11/xbindkeysrc"

[ -f "$userresources" ]   && xrdb -merge "$userresources"
[ -f "$userkeybindings" ] && xbindkeys -f "$userkeybindings"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# X server settings
xsetroot -cursor_name left_ptr &
xset r rate 500 50
xdsc run &

# startup programs
dunst &
udiskie -s &
picom -b &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 & # todo: replace with simplier auth agent
clipmenud &
redshiftw &
unclutter &
nm-applet &
wallpaper restore &
solaar -w hide &

DESKTOP_SESSION="${DESKTOP_SESSION:-i3}" # default session
export DESKTOP_SESSION

echo "Stating session: '$DESKTOP_SESSION'"
exec "$DESKTOP_SESSION"

# vi: syntax=sh
