name:                xmonad-pavulon
version:             0.1.0.0
author:              "pavulonx"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- xmonad >= 0.17
- xmonad-contrib >= 0.17
- X11
- containers
- text
- directory
- utf8-string
- dbus

library:
  source-dirs: .

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-pavulon

  xmonadctl:
    main:                xmonadctl.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
